### ISSUE TITLE
Support for Unicode 11.0 fields, such as kKoreanEducationHanja / kKoreanName

### ISSUE THREAD

**Issue by combacsa** [cihai/unihan-etl#91]
Hello. Recent Unicode 11.0 standard release introduced several new fields, such as kKoreanEducationHanja / kKoreanName / etc.

(Refer to <https://www.unicode.org/reports/tr38/index.html#kKoreanName>)

It would be very nice if unihan-etl supports such new fields.

**Comment by tony** [comment]
Sounds like a good idea.

**Comment by tony** [comment]
# Unicode 11.0.0 (2018-05-18)

https://www.unicode.org/reports/tr38/

# [Changes](https://www.unicode.org/reports/tr38/#Modifications)

- Reissued for Unicode 11.0.0.
- Updated the description and regular expression for the kHangul field.
- Updated the regular expressions for the kIRG_KSource and kIRG_USource field.
- Added the kJinmeiyoKanji, kJoyoKanji, kKoreanEducationHanja, kKoreanName, and kTGH fields.
- Updated range of covered characters to include U+9FEB through U+9FEF.
- Added section [2.1.1](https://www.unicode.org/reports/tr38/#PropertyExtension).
- Made corrections to the source descriptions for kGB7, kGB7, kIRG_GSource, kIRG_JSource, and kIRG_KSource fields.

See also: #93 (Updates for [Unicode 10.0](https://www.unicode.org/reports/tr38/tr38-23.html), 2017-06-15)

**Comment by tony** [comment]
@combacsa This is up in v0.10.0!
